apiVersion: v2
name: vaultwarden
description: vaultwarden is an unofficial Bitwarden-compatible server written in Rust
type: application
keywords:
  - Rust
  - vaultwarden
sources:
  - https://github.com/guerzon/vaultwarden
  - https://github.com/dani-garcia/vaultwarden
appVersion: 1.30.3
maintainers:
  - name: guerzon
    email: guerzon@proton.me
    url: https://github.com/guerzon
version: 0.22.3
kubeVersion: ">=1.12.0-0"
